# Generated by Django 5.2.12 on 2026-03-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsync',
            name='data_dict',
            field=models.CharField(default={}, max_length=64),
            preserve_default=False,
        ),
    ]
