# Generated by Django 5.2.12 on 2026-03-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0002_productsync_data_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsync',
            name='data_dict',
            field=models.CharField(max_length=255),
        ),
    ]
