# Generated by Django 5.2.12 on 2026-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0003_alter_productsync_data_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('data_dict', models.CharField(max_length=255)),
                ('error_message', models.CharField(max_length=255)),
                ('data_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
