# Generated by Django 5.2.12 on 2026-03-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0004_dataqualitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualitylog',
            name='error_message',
            field=models.CharField(max_length=1024),
        ),
    ]
