# Generated by Django 5.2.12 on 2026-03-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0005_alter_dataqualitylog_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualitylog',
            name='data_dict',
            field=models.CharField(max_length=1024),
        ),
    ]
